[project]
name = "DroneFlyer"
version = "0.1.0"
description = "Drone simulation program"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "pygame>=2.6.1",
    "pyqt5>=5.15.11",
]
